curl 'http://www-web-mis-nonauth.tiaofangzi.com/opportunity/sendSmsCode' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh,en;q=0.9,zh-CN;q=0.8,ko;q=0.7' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'Origin: http://www.hualala.com' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://www.hualala.com/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  --data-raw '{"mobile":"18226791322"}' \
  --compressed \
  --insecure
